server:
  port: ${SERVER_PORT:8040}
  servlet:
    context-path: /order_service
grpc:
  server:
    port: ${GRPC_PORT:9040}
    inventory_server: ${GRPC_INVENTORY_SERVER:localhost:9030}
    product_server: ${GRPC_PRODUCT_SERVER:localhost:9020}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
security:
  enable: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
mysql:
  url: ${MYSQL_DB_URL:jdbc:mysql://host:port/hugio_order_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${MYSQL_DB_USERNAME:root}
  password: ${MYSQL_DB_PASSWORD:123456}
  driver_class_name: org.postgresql.Driver
  ddl_auto: none
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
aes_secret_key: iXlCmp4pcEZ2YBUqfelapUH2wGRDDSar
auth:
  endpoint: ${AUTH_ENDPOINT:https://hugio.ngrok.app/auth_service/auth/retrieve-info}
kafka:
  server: ${KAFKA_SERVER:127.0.0.1:9092}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
  group-id: ${KAFKA_GROUP_ID:hugio_listener}
chat:
  api:
    key: ${CHAT_API_KEY:}
logging:
  level:
    org:
      hibernate:
        nodeValue: info
        stat: debug
        SQL_SLOW: info
        SQL: debug
        cache: debug
        orm:
          jdbc:
            bind: trace
