image:
  name: tuanloc/hugio
  tag: auth-service
tcp_port: 8010
tcp_svc_type: NodePort
grpc_port: 9010
replica: 1
database_username: cm9vdA==
database_password: MTIzNDU2
default_password: SHVnaW8hQCMxMjM=