apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      volumes:
        - name: log
          emptyDir: {}
      containers:
        - name: auth-service
          volumeMounts:
            - mountPath: /app/data/log
              name: log
          image: tuanloc/project:auth-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 9000
          env:
            - name: APPLICATION_NAME
              value: "auth-service"
            - name: LOG_FILE_NAME
              value: "auth-service"
            - name: MYSQL_DB_URL
              value: "jdbc:mysql://host.docker.internal:3306/hugio_user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "tyZnEfTQhn"
#  kubectl apply -f deploy.yml -n ingress-nginx
#  kubectl delete -f deploy.yml -n ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc-1
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: "TCP"
      name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc-2
  labels:
    app: auth-service
spec:
  clusterIP: None
  selector:
    app: auth-service
  ports:
    - port: 9000
      targetPort: 9000
