apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replica }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: log
          emptyDir: {}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.tcp_port }}
            - containerPort: {{ .Values.grpc_port }}
          env:
            - name: MYSQL_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: database_url
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: database_username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: database_password
            - name: GRPC_AUTH_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cf
                  key: auth_grpc_endpoint
