apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replica }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: log
          emptyDir: {}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: {{ .Values.tcp_port }}
            - containerPort: {{ .Values.grpc_port }}
          env:
            - name: GRPC_AUTH_SERVER
              value: "auth-service-svc-2:9000"
            - name: GRPC_INVENTORY_SERVER
              value: "inventory-service-svc-2:9030"
            - name: DB_URL
              value: "jdbc:postgresql://192.168.1.22:3306/hugio_product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: database_password
            - name: AUTH_ENDPOINT
              value: "http://auth-service-svc-1:8000/auth_service/auth/retrieve-info"
            - name: QR_CODE_API_URL
              value: "https://api.qr-code-generator.com/v1/create?access-token=BWiEFWRPYY6TzdkZ5jmPd_CK-T5QblYFlyyzw91SDWBJ0MnhN8V7uu-xYrTykoon"
            - name: CHAT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: chat_gpt_key
            - name: REDIS_HOST
              value: "192.168.1.22"
            - name: REDIS_PORT
              value: "6378"
            - name: KAFKA_SERVER
              value: "192.168.1.22:9092"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_SASL_MECHANISM
              value: "GSSAPI"
            - name: KAFKA_GROUP_ID
              value: "hugio_listener"
