apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_username: {{ .Values.database.username }}
  chat_api_key: {{ .Values.chat.api_key }}