apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-2
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.grpc_port }}
      targetPort: {{ .Values.grpc_port }}