apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_username: {{ .Values.database_username }}
  database_password: {{ .Values.database_password }}
  chat_gpt_key: {{ .Values.chat_gpt_key }}
