apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_username: {{ .Values.database.username }}
  database_password: {{ .Values.database.password }}