def artifactId = ""
def dockerImage = ""
def dockerTag = "latest"
def userIdCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
def now = (new Date()).format("yyMMddHHmmss", TimeZone.getTimeZone('Asia/Ho_Chi_Minh'))

pipeline {
    agent any
    tools {
        maven "mvn-3.9.3"
        jdk "jdk17"
    }
    environment {
        DOCKER_REGISTRY = '091976145410.dkr.ecr.ap-southeast-1.amazonaws.com'
        K8S_NAMESPACE = 'omni-cib'
        K8S_CONTEXT = 'arn:aws:eks:ap-southeast-1:091976145410:cluster/nb-eks-dev'
        AWS_REGION = 'ap-southeast-1'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean install -DskipTests=true -Dfile.encoding=UTF8 -f pom.xml'
                }
            }
        }
    }
}