def dockerImage = "localhost:6000/hugio"
def authDockerTag = ""
def userDockerTag = ""
def productDockerTag = ""
def authProjectId = ""
def userProjectId = ""
def productProjectId = ""
def userIdCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
def now = (new Date()).format("yyMMddHHmmss", TimeZone.getTimeZone('Asia/Ho_Chi_Minh'))

pipeline {
    agent any
    //options {
    //    // Disallow concurrent executions of the Pipeline. Can be useful
    //    // for preventing simultaneous accesses to shared resources, etc.
    //    disableConcurrentBuilds()
    //}
    // as a step in a scripted pipeline
    //properties([disableConcurrentBuilds(abortPrevious: true)])
    // as a directive in a declarative pipeline
    options { disableConcurrentBuilds abortPrevious: true }
    tools {
        maven "3.9.3"
        jdk "17"
    }
    environment {
        K8S_NAMESPACE = 'hugio'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean install -DskipTests=true -Dfile.encoding=UTF8 -f pom.xml'
                }
            }
        }
        stage('Copy source') {
            steps {
                script {
                    dir ("hugio-auth-service") {
                        authProjectId = sh script: 'mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout', returnStdout: true
                        authDockerTag = authProjectId.replace("-", "_") + '_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/auth_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                    }
                    dir ("hugio-user-service") {
                        userProjectId = sh script: 'mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout', returnStdout: true
                        userDockerTag = userProjectId.replace("-", "_") + '_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/user_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/user_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/user_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/user_service'
                    }
                    dir ("hugio-product-service") {
                        productProjectId = sh script: 'mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout', returnStdout: true
                        productDockerTag = productProjectId.replace("-", "_") + '_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/product_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/product_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/product_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/product_service'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 \"cd /home/ae403/hugio/auth_service && docker build . -t ${dockerImage}:${authDockerTag} && docker push ${dockerImage}:${authDockerTag} && docker rmi ${dockerImage}:${authDockerTag} && helm upgrade -i --set image.name=${dockerImage},image.tag=${authDockerTag} -n ${K8S_NAMESPACE} ${authProjectId} ./helm_chart\""
                    sh "ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 \"cd /home/ae403/hugio/user_service && docker build . -t ${dockerImage}:${userDockerTag} && docker push ${dockerImage}:${userDockerTag} && docker rmi ${dockerImage}:${userDockerTag} && helm upgrade -i --set image.name=${dockerImage},image.tag=${userDockerTag} -n ${K8S_NAMESPACE} ${userProjectId} ./helm_chart\""
                    sh "ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 \"cd /home/ae403/hugio/product_service && docker build . -t ${dockerImage}:${productDockerTag} && docker push ${dockerImage}:${productDockerTag} && docker rmi ${dockerImage}:${productDockerTag} && helm upgrade -i --set image.name=${dockerImage},image.tag=${productDockerTag} -n ${K8S_NAMESPACE} ${productProjectId} ./helm_chart\""
                }
            }
        }
    }
}