def dockerImage = "tuanloc/hugio"
def authDockerTag = ""
def userDockerTag = ""
def productDockerTag = ""
def userIdCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
def now = (new Date()).format("yyMMddHHmmss", TimeZone.getTimeZone('Asia/Ho_Chi_Minh'))

pipeline {
    agent any
    tools {
        maven "3.9.3"
        jdk "17"
    }
    environment {
        K8S_NAMESPACE = 'hugio'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean install -DskipTests=true -Dfile.encoding=UTF8 -f pom.xml'
                }
            }
        }
        stage('Deploy auth service') {
            steps {
                script {
                    dir ("hugio-auth-service") {
                        authDockerTag = dockerImage + 'auth_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/auth_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/auth_service'
                    }
                }
            }
        }
        stage('Deploy user service') {
            steps {
                script {
                    dir ("hugio-user-service") {
                        userDockerTag = dockerImage + 'user_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/user_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/user_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/user_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/user_service'
                    }
                }
            }
        }
        stage('Deploy product service') {
            steps {
                script {
                    dir ("hugio-product-service") {
                        productDockerTag = dockerImage + 'product_' + now
                        sh 'ssh -i /var/jenkins_home/jenkins ae403@192.168.1.22 "mkdir -p /home/ae403/hugio/product_service"'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./helm_chart ae403@192.168.1.22:/home/ae403/hugio/product_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./target ae403@192.168.1.22:/home/ae403/hugio/product_service'
                        sh 'scp -i /var/jenkins_home/jenkins -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no Dockerfile ae403@192.168.1.22:/home/ae403/hugio/product_service'
                    }
                }
            }
        }
    }
}