apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      volumes:
        - name: log
          emptyDir: {}
      containers:
        - name: inventory-service
          image: tuanloc/hugio:inventory-service
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8010
            - containerPort: 9010
          env:
            - name: APPLICATION_NAME
              value: "inventory-service"
            - name: LOG_FILE_NAME
              value: "inventory-service"
            - name: MYSQL_DB_URL
              value: "jdbc:mysql://host.docker.internal:3306/hugio_user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "tyZnEfTQhn"
            - name: GRPC_AUTH_SERVER
              value: auth-service-svc-2:9000
#  kubectl apply -f deploy.yml -n ingress-nginx
#  kubectl delete -f deploy.yml -n ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc-1
  labels:
    app: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - protocol: "TCP"
      name: http
      port: 8010
      targetPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc-2
  labels:
    app: inventory-service
spec:
  clusterIP: None
  selector:
    app: inventory-service
  ports:
    - port: 9010
      targetPort: 9010
