server:
  port: ${SERVER_PORT:8020}
  servlet:
    context-path: /product_service
grpc:
  server:
    port: ${GRPC_PORT:9020}
    auth_server: ${GRPC_AUTH_SERVER:localhost:9000}
    inventory_server: ${GRPC_INVENTORY_SERVER:localhost:9030}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
mysql:
  url: ${MYSQL_DB_URL:jdbc:mysql://host:port/hugio_product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${MYSQL_DB_USERNAME:root}
  password: ${MYSQL_DB_PASSWORD:123456}
  driver_class_name: com.mysql.cj.jdbc.Driver
  ddl_auto: update
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
auth:
  endpoint: ${AUTH_ENDPOINT:http://192.168.1.22:8000/auth_service/auth/retrieve-info}
qr:
  code:
    api-url: ${QR_CODE_API_URL:https://api.qr-code-generator.com/v1/create?access-token=QjA1SUNdr2dck1C9mBZPMCAQDWZgYJ9sxV4vE59kZPXkdP4RjQxuvzKE8Tge8MtR}
chat:
  api:
    key: ${CHAT_API_KEY:}
