server:
  port: ${SERVER_PORT:8020}
  servlet:
    context-path: /product_service
grpc:
  server:
    port: ${GRPC_PORT:9020}
    auth_server: ${GRPC_AUTH_SERVER:localhost:9000}
    inventory_server: ${GRPC_INVENTORY_SERVER:localhost:9030}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
postgresql:
  url: ${DB_URL:jdbc:postgresql://host:port/hugio_product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:123456}
  driver_class_name: org.postgresql.Driver
  ddl_auto: none
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
auth:
  endpoint: ${AUTH_ENDPOINT:http://192.168.1.22:8000/auth_service/auth/retrieve-info}
qr:
  code:
    api-url: ${QR_CODE_API_URL:https://api.qr-code-generator.com/v1/create?access-token=QjA1SUNdr2dck1C9mBZPMCAQDWZgYJ9sxV4vE59kZPXkdP4RjQxuvzKE8Tge8MtR}
chat:
  api:
    key: ${CHAT_API_KEY:}
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6378}
kafka:
  server: ${KAFKA_SERVER:127.0.0.1:9092}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
  group-id: ${KAFKA_GROUP_ID:hugio_listener}
logging:
  level:
    org:
      hibernate:
        nodeValue: info
        stat: debug
        SQL_SLOW: info
        SQL: debug
        cache: debug
        orm:
          jdbc:
            bind: trace
