server:
  port: ${SERVER_PORT:8030}
  servlet:
    context-path: /user_service
grpc:
  server:
    port: ${GRPC_PORT:9030}
    auth_server: ${GRPC_AUTH_SERVER:localhost:9000}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
security:
  enable: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
mysql:
  url: ${MYSQL_DB_URL:jdbc:mysql://0.tcp.ap.ngrok.io:17056/hugio_inventory_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${MYSQL_DB_USERNAME:root}
  password: ${MYSQL_DB_PASSWORD:123456}
  driver_class_name: com.mysql.cj.jdbc.Driver
  ddl_auto: update
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
aes_secret_key: iXlCmp4pcEZ2YBUqfelapUH2wGRDDSar
auth:
  endpoint: ${AUTH_ENDPOINT:http://192.168.1.22:8000/auth_service/auth/retrieve-info}
kafka:
  server: ${KAFKA_SERVER:127.0.0.1:9092}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
  group-id: ${KAFKA_GROUP_ID:hugio_listener}
  topic:
    create: inventory_create
    import_product: inventory_import_product
    update_product: inventory_update_product
    reduce_product_quantity: inventory_reduce_product_quantity
