server:
  port: ${SERVER_PORT:8010}
  servlet:
    context-path: /user_service
grpc:
  server:
    port: ${GRPC_PORT:9010}
    auth_server: ${GRPC_AUTH_SERVER:localhost:9000}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
security:
  enable: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
postgresql:
  url: ${DB_URL:jdbc:postgresql://host:port/hugio_user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:123456}
  driver_class_name: org.postgresql.Driver
  ddl_auto: none
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
aes_secret_key: iXlCmp4pcEZ2YBUqfelapUH2wGRDDSar
auth:
  endpoint: ${AUTH_ENDPOINT:https://hugio.ngrok.app/auth_service/auth/retrieve-info}
default_password: ${DEFAULT_PASSWORD:}
logging:
  level:
    org:
      hibernate:
        nodeValue: info
        stat: debug
        SQL_SLOW: info
        SQL: debug
        cache: debug
        orm:
          jdbc:
            bind: trace
