-- hugio_inventory_db.INVENTORY_LOG definition

CREATE TABLE `INVENTORY_LOG` (
  `ACTIVE` bit(1) NOT NULL,
  `IMPORTED_FEE` double DEFAULT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `IMPORTED_QUANTITY` bigint DEFAULT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  `BEHAVIOUR` enum('CREATE','IMPORT','UPDATE') NOT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `IMPORTED_BY` varchar(255) DEFAULT NULL,
  `IMPORTED_FROM` varchar(255) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  `PRODUCT_UID` varchar(255) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- hugio_inventory_db.PRODUCT_INVENTORY definition

CREATE TABLE `PRODUCT_INVENTORY` (
  `ACTIVE` bit(1) NOT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `QUANTITY` bigint DEFAULT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  `version` bigint DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `PRODUCT_UID` varchar(255) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;